using Microsoft.CodeAnalysis;

namespace ComputeWeave.Core.SourceGenerators;

/// <summary>
/// A source generator to create global using directives for the HLSL primitive types.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GlobalUsingDirectivesGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The generated global using directives to emit.
    /// </summary>
    private const string GlobalUsingDirectives =
        """
        // <auto-generated/>
        #pragma warning disable

        global using bool2 = global::ComputeWeave.Bool2;
        global using bool3 = global::ComputeWeave.Bool3;
        global using bool4 = global::ComputeWeave.Bool4;
        global using bool1x1 = global::ComputeWeave.Bool1x1;
        global using bool1x2 = global::ComputeWeave.Bool1x2;
        global using bool1x3 = global::ComputeWeave.Bool1x3;
        global using bool1x4 = global::ComputeWeave.Bool1x4;
        global using bool2x1 = global::ComputeWeave.Bool2x1;
        global using bool2x2 = global::ComputeWeave.Bool2x2;
        global using bool2x3 = global::ComputeWeave.Bool2x3;
        global using bool2x4 = global::ComputeWeave.Bool2x4;
        global using bool3x1 = global::ComputeWeave.Bool3x1;
        global using bool3x2 = global::ComputeWeave.Bool3x2;
        global using bool3x3 = global::ComputeWeave.Bool3x3;
        global using bool3x4 = global::ComputeWeave.Bool3x4;
        global using bool4x1 = global::ComputeWeave.Bool4x1;
        global using bool4x2 = global::ComputeWeave.Bool4x2;
        global using bool4x3 = global::ComputeWeave.Bool4x3;
        global using bool4x4 = global::ComputeWeave.Bool4x4;
        global using double2 = global::ComputeWeave.Double2;
        global using double3 = global::ComputeWeave.Double3;
        global using double4 = global::ComputeWeave.Double4;
        global using double1x1 = global::ComputeWeave.Double1x1;
        global using double1x2 = global::ComputeWeave.Double1x2;
        global using double1x3 = global::ComputeWeave.Double1x3;
        global using double1x4 = global::ComputeWeave.Double1x4;
        global using double2x1 = global::ComputeWeave.Double2x1;
        global using double2x2 = global::ComputeWeave.Double2x2;
        global using double2x3 = global::ComputeWeave.Double2x3;
        global using double2x4 = global::ComputeWeave.Double2x4;
        global using double3x1 = global::ComputeWeave.Double3x1;
        global using double3x2 = global::ComputeWeave.Double3x2;
        global using double3x3 = global::ComputeWeave.Double3x3;
        global using double3x4 = global::ComputeWeave.Double3x4;
        global using double4x1 = global::ComputeWeave.Double4x1;
        global using double4x2 = global::ComputeWeave.Double4x2;
        global using double4x3 = global::ComputeWeave.Double4x3;
        global using double4x4 = global::ComputeWeave.Double4x4;
        global using float2 = global::ComputeWeave.Float2;
        global using float3 = global::ComputeWeave.Float3;
        global using float4 = global::ComputeWeave.Float4;
        global using float1x1 = global::ComputeWeave.Float1x1;
        global using float1x2 = global::ComputeWeave.Float1x2;
        global using float1x3 = global::ComputeWeave.Float1x3;
        global using float1x4 = global::ComputeWeave.Float1x4;
        global using float2x1 = global::ComputeWeave.Float2x1;
        global using float2x2 = global::ComputeWeave.Float2x2;
        global using float2x3 = global::ComputeWeave.Float2x3;
        global using float2x4 = global::ComputeWeave.Float2x4;
        global using float3x1 = global::ComputeWeave.Float3x1;
        global using float3x2 = global::ComputeWeave.Float3x2;
        global using float3x3 = global::ComputeWeave.Float3x3;
        global using float3x4 = global::ComputeWeave.Float3x4;
        global using float4x1 = global::ComputeWeave.Float4x1;
        global using float4x2 = global::ComputeWeave.Float4x2;
        global using float4x3 = global::ComputeWeave.Float4x3;
        global using float4x4 = global::ComputeWeave.Float4x4;
        global using int2 = global::ComputeWeave.Int2;
        global using int3 = global::ComputeWeave.Int3;
        global using int4 = global::ComputeWeave.Int4;
        global using int1x1 = global::ComputeWeave.Int1x1;
        global using int1x2 = global::ComputeWeave.Int1x2;
        global using int1x3 = global::ComputeWeave.Int1x3;
        global using int1x4 = global::ComputeWeave.Int1x4;
        global using int2x1 = global::ComputeWeave.Int2x1;
        global using int2x2 = global::ComputeWeave.Int2x2;
        global using int2x3 = global::ComputeWeave.Int2x3;
        global using int2x4 = global::ComputeWeave.Int2x4;
        global using int3x1 = global::ComputeWeave.Int3x1;
        global using int3x2 = global::ComputeWeave.Int3x2;
        global using int3x3 = global::ComputeWeave.Int3x3;
        global using int3x4 = global::ComputeWeave.Int3x4;
        global using int4x1 = global::ComputeWeave.Int4x1;
        global using int4x2 = global::ComputeWeave.Int4x2;
        global using int4x3 = global::ComputeWeave.Int4x3;
        global using int4x4 = global::ComputeWeave.Int4x4;
        global using uint2 = global::ComputeWeave.UInt2;
        global using uint3 = global::ComputeWeave.UInt3;
        global using uint4 = global::ComputeWeave.UInt4;
        global using uint1x1 = global::ComputeWeave.UInt1x1;
        global using uint1x2 = global::ComputeWeave.UInt1x2;
        global using uint1x3 = global::ComputeWeave.UInt1x3;
        global using uint1x4 = global::ComputeWeave.UInt1x4;
        global using uint2x1 = global::ComputeWeave.UInt2x1;
        global using uint2x2 = global::ComputeWeave.UInt2x2;
        global using uint2x3 = global::ComputeWeave.UInt2x3;
        global using uint2x4 = global::ComputeWeave.UInt2x4;
        global using uint3x1 = global::ComputeWeave.UInt3x1;
        global using uint3x2 = global::ComputeWeave.UInt3x2;
        global using uint3x3 = global::ComputeWeave.UInt3x3;
        global using uint3x4 = global::ComputeWeave.UInt3x4;
        global using uint4x1 = global::ComputeWeave.UInt4x1;
        global using uint4x2 = global::ComputeWeave.UInt4x2;
        global using uint4x3 = global::ComputeWeave.UInt4x3;
        global using uint4x4 = global::ComputeWeave.UInt4x4;
        """;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context => context.AddSource($"{nameof(GlobalUsingDirectives)}.g.cs", GlobalUsingDirectives));
    }
}