<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SupportedOSPlatformVersion>6.2</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ComputeWeave.D3D12MemoryAllocator, PublicKey=$(AssemblySignPublicKey)" />
    <InternalsVisibleTo Include="ComputeWeave.Dxc, PublicKey=$(AssemblySignPublicKey)" />
    <InternalsVisibleTo Include="ComputeWeave.Tests.Internals, PublicKey=$(AssemblySignPublicKey)" />
    <InternalsVisibleTo Include="ComputeWeave.Tests.SourceGenerators, PublicKey=$(AssemblySignPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComputeWeave.Core\ComputeWeave.Core.csproj" />
  </ItemGroup>

  <!-- Include the ILLink file (to properly trim configuration switches in publish builds) -->
  <ItemGroup>
    <EmbeddedResource Include="Properties\ILLink.Substitutions.xml" LogicalName="ILLink.Substitutions.xml" />
  </ItemGroup>

  <!-- T4 template generation service (the .tt/.g.cs files are resolved in the .targets file) -->
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <!-- Shared ComputeWeave.Win32.D3D12 with D3D12 bindings -->
  <Import Project="..\ComputeWeave.Win32.D3D12\ComputeWeave.Win32.D3D12.projitems" Label="Shared" />
</Project>
