<Project>

  <!-- Get the analyzer from the ComputeWeave NuGet package -->
  <Target Name="_ComputeWeaveGatherAnalyzers">
    <ItemGroup>
      <_ComputeWeaveAnalyzer Include="@(Analyzer)" Condition="'%(Analyzer.NuGetPackageId)' == 'ComputeWeave'" />
    </ItemGroup>
  </Target>

  <!-- Remove the analyzer if using Roslyn < 4.9 (ComputeWeave's generators require Roslyn 4.9) -->
  <Target Name="_ComputeWeaveRemoveAnalyzersForRoslyn3"
          Condition="'$(CSharpCoreTargetsPath)' != ''"
          AfterTargets="ResolvePackageDependenciesForBuild;ResolveNuGetPackageAssets"
          DependsOnTargets="_ComputeWeaveGatherAnalyzers">

    <!--
      Use the CSharpCoreTargetsPath property to find the version of the compiler we are using. This is the same mechanism
      MSBuild uses to find the compiler. We could check the assembly version for any compiler assembly (since they all have
      the same version) but Microsoft.Build.Tasks.CodeAnalysis.dll is where MSBuild loads the compiler tasks from so if
      someone is getting creative with msbuild tasks/targets this is the "most correct" assembly to check.
    -->
    <GetAssemblyIdentity AssemblyFiles="$([System.IO.Path]::Combine(`$([System.IO.Path]::GetDirectoryName($(CSharpCoreTargetsPath)))`,`Microsoft.Build.Tasks.CodeAnalysis.dll`))">
      <Output TaskParameter="Assemblies" ItemName="ComputeWeaveCurrentCompilerAssemblyIdentity"/>
    </GetAssemblyIdentity>

    <PropertyGroup>

      <!-- Transform the resulting item from GetAssemblyIdentity into a property representing its assembly version -->
      <ComputeWeaveCurrentCompilerVersion>@(ComputeWeaveCurrentCompilerAssemblyIdentity->'%(Version)')</ComputeWeaveCurrentCompilerVersion>

      <!-- The CurrentCompilerVersionIsNotNewEnough property can now be defined based on the Roslyn assembly version -->
      <ComputeWeaveCurrentCompilerVersionIsNotNewEnough Condition="$([MSBuild]::VersionLessThan($(ComputeWeaveCurrentCompilerVersion), 4.9))">true</ComputeWeaveCurrentCompilerVersionIsNotNewEnough>
    </PropertyGroup>

    <!-- If the Roslyn version is < 4.9, disable the source generators -->
    <ItemGroup Condition ="'$(ComputeWeaveCurrentCompilerVersionIsNotNewEnough)' == 'true'">
      <Analyzer Remove="@(_ComputeWeaveAnalyzer)"/>
    </ItemGroup>

    <!--
      If the source generators are disabled, also emit an error. This would've been produced by MSBuild itself as well, but
      emitting this manually lets us customize the message to inform developers as to why exactly the generators have been
      disabled, and that ComputeWeave will not work at all unless a more up to date IDE or compiler version are used.
    -->
    <Error Condition ="'$(ComputeWeaveCurrentCompilerVersionIsNotNewEnough)' == 'true'" Text="The ComputeWeave source generators have been disabled on the current configuration, as they need Roslyn 4.9 in order to work. ComputeWeave requires the source generators to run in order to process shaders, so the library cannot be used without a more up to date IDE (eg. VS 2022 17.8 or greater) or .NET SDK version (.NET 8 SDK or greater)."/>
  </Target>
  
  <!-- Remove the analyzer if Roslyn is missing -->
  <Target Name="_ComputeWeaveRemoveAnalyzersForRosynNotFound"
          Condition="'$(CSharpCoreTargetsPath)' == ''"
          AfterTargets="ResolvePackageDependenciesForBuild;ResolveNuGetPackageAssets"
          DependsOnTargets="_ComputeWeaveGatherAnalyzers">

    <!-- If no Roslyn assembly could be found, just remove the analyzer without emitting a warning -->
    <ItemGroup>
      <Analyzer Remove="@(_ComputeWeaveAnalyzer)"/>
    </ItemGroup>
  </Target>

  <!-- Automatically set the configuration switches -->
  <ItemGroup>

    <!-- COMPUTEWEAVE_ENABLE_DEBUG_OUTPUT switch -->
    <RuntimeHostConfigurationOption Condition="'$(ComputeWeaveEnableDebugOutput)' != ''"
                                    Include="COMPUTEWEAVE_ENABLE_DEBUG_OUTPUT"
                                    Value="$(ComputeWeaveEnableDebugOutput)"
                                    Trim="true" />

    <!-- COMPUTEWEAVE_ENABLE_DEVICE_REMOVED_EXTENDED_DATA switch -->
    <RuntimeHostConfigurationOption Condition="'$(ComputeWeaveEnableDeviceRemovedExtendedData)' != ''"
                                    Include="COMPUTEWEAVE_ENABLE_DEVICE_REMOVED_EXTENDED_DATA"
                                    Value="$(ComputeWeaveEnableDeviceRemovedExtendedData)"
                                    Trim="true" />

    <!-- COMPUTEWEAVE_ENABLE_GPU_TIMEOUT switch -->
    <RuntimeHostConfigurationOption Condition="'$(ComputeWeaveEnableGpuTimeout)' != ''"
                                    Include="COMPUTEWEAVE_ENABLE_GPU_TIMEOUT"
                                    Value="$(ComputeWeaveEnableGpuTimeout)"
                                    Trim="true" />
  </ItemGroup>

</Project>
